### ISSUE TITLE
Open-API

### ISSUE THREAD

**Issue by febryanmz** [GP2-Kelompok1/BE-Project-2#1]

**Comment by febryanmz** [comment]
Open-API
1. Auth
2. Users > done
3. Teams
4. Classes
5. Mentees
6. Feedbacks

**Comment by febryanmz** [comment]
Open-API

Auth
Users > done
Teams > done
Classes
Mentees
Feedbacks

**Comment by febryanmz** [comment]
Open-API

1. Auth
2. Users > done
3. Teams > done
4. Classes > done
5. Mentees
6. Feedbacks
7. Swaggerhub server

**Comment by DevWiku** [comment]
Open-API

Auth
Users > done
Teams > done
Classes > done
Mentees > done
Feedbacks > done
Swaggerhub server
